#include "Agence.h"




void Agence::Créer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:0000000000000869 begin
{
}
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:0000000000000869 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Agence::Supprimer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:0000000000000876 begin
{
}
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:0000000000000876 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Agence::Visualiser()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008AD begin
{
}
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008AD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Agence::RattacherPersonnel()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008AF begin
{
}
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008AF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Agence::DétacherPersonnel()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008B1 begin
{
}
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008B1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
