#include "Direction générale.h"




void Direction générale::Consulter()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008B5 begin
{
}
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008B5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Direction générale::CréerAgence()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008B7 begin
{
}
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008B7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Direction générale::SupprimerAgence()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008B9 begin
{
}
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008B9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
