#include "Personnels.h"




void Personnels::créer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008A1 begin
{
}
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008A1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Personnels::Supprimer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008A3 begin
{
}
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008A3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Personnels::Rechercher()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008A5 begin
{
}
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008A5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Personnels::Modifier()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008A7 begin
{
}
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008A7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Personnels::Rechercher()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008A9 begin
{
}
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008A9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Personnels::RattacherALagence()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008AB begin
{
}
// section -64--88-19-1--7be4c8fb:16ef40074c2:-8000:00000000000008AB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
